name: Build API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: a
      uses: actions/checkout@v3

    - name: b
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        
    - name: c
      run: pip install flask

 
